"""
Handles loading patient data from CSV and initializing the SQLite database.
Provides the SQLConnector component for executing SQL queries generated by the LLM.
"""
import re
import sqlite3
from typing import List

import pandas as pd
from haystack import component
from haystack.dataclasses import ChatMessage


def setup_database(
    csv_path: str = "dermatology_patient_data.csv",
    db_path: str = "patient_data.db",
) -> None:
    df = pd.read_csv(csv_path, encoding="utf-8-sig", delimiter=";")
    conn = sqlite3.connect(db_path)
    df.to_sql("patients", conn, if_exists="replace", index=False)
    conn.close()


@component
class SQLConnector:
    def __init__(self, sql_database: str):
        self.connection = sqlite3.connect(sql_database, check_same_thread=False)

    @component.output_types(results=List[str])
    def run(self, llm_replies: List[ChatMessage]):
        results = []
        pattern = r"```sql\s*([\s\S]+?)```"

        for message in llm_replies:
            extracted = re.findall(pattern, message.text)
            if not extracted:
                results.append("No SQL code found.")
                continue

            sql_to_run = " ".join(extracted[0].splitlines()).strip()
            try:
                result = pd.read_sql(sql_to_run, self.connection)
                results.append(str(result))
            except Exception as e:
                results.append(f"Error: {e}")

        return {"results": results}
